[package]
name = "ultrakrust"
description = "ULTRAKILL movement sandbox in Bevy"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
uk-core = { path = "../uk-core" }
bevy.workspace = true
uk-assets = { path = "../uk-assets" }
uk-game = { path = "../uk-game" }
naga = { version = "29.0.4", features = ["spv-in", "wgsl-out"] }
wgpu-types = "29.0.4"
bytemuck = "1.25.2"
